/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification
 * OpenApi documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gpatrik101@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookResponse
 */
export interface BookResponse {
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'authorName'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'isbn'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'synopsis'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'owner'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'bookCoverUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    'rate'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BookResponse
     */
    'archived'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BookResponse
     */
    'shareable'?: boolean;
}

