/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification
 * OpenApi documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gpatrik101@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookRequest
 */
export interface BookRequest {
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    'authorName': string;
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    'isbn': string;
    /**
     * 
     * @type {string}
     * @memberof BookRequest
     */
    'synopsis': string;
    /**
     * 
     * @type {boolean}
     * @memberof BookRequest
     */
    'shareable'?: boolean;
}

