/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification
 * OpenApi documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gpatrik101@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeedbackResponse
 */
export interface FeedbackResponse {
    /**
     * 
     * @type {number}
     * @memberof FeedbackResponse
     */
    'rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackResponse
     */
    'comment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackResponse
     */
    'ownFeedback'?: boolean;
}

