/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification
 * OpenApi documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gpatrik101@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BorrowedBookResponse } from './borrowed-book-response';

/**
 * 
 * @export
 * @interface PageResponseBorrowedBookResponse
 */
export interface PageResponseBorrowedBookResponse {
    /**
     * 
     * @type {Array<BorrowedBookResponse>}
     * @memberof PageResponseBorrowedBookResponse
     */
    'content'?: Array<BorrowedBookResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseBorrowedBookResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseBorrowedBookResponse
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseBorrowedBookResponse
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseBorrowedBookResponse
     */
    'totalPages'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseBorrowedBookResponse
     */
    'first'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseBorrowedBookResponse
     */
    'last'?: boolean;
}

