/* tslint:disable */
/* eslint-disable */
/**
 * OpenApi specification
 * OpenApi documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gpatrik101@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FeedbackResponse } from './feedback-response';

/**
 * 
 * @export
 * @interface PageResponseFeedbackResponse
 */
export interface PageResponseFeedbackResponse {
    /**
     * 
     * @type {Array<FeedbackResponse>}
     * @memberof PageResponseFeedbackResponse
     */
    'content'?: Array<FeedbackResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseFeedbackResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseFeedbackResponse
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseFeedbackResponse
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseFeedbackResponse
     */
    'totalPages'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseFeedbackResponse
     */
    'first'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseFeedbackResponse
     */
    'last'?: boolean;
}

