services:
  postgres:
    container_name: postgres-sql-bs
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_sweeper
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: maildev-bs
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    environment:
        MAILDEV_IP: "::"
  bs-api:
    container_name: bs-api
    image: cicau/book-sweeper-backend:1.0.4
    ports:
      - 8088:8088
    networks:
        - spring-demo
    depends_on:
      - postgres
  bs-ui:
    container_name: bs-ui
    image: uibs/uibs:1.0.0
    ports:
      - 8080:80
    networks:
        - spring-demo
    depends_on:
      - bs-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local