services:
  postgres:
    container_name: postgres-sql-bs
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_sweeper
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: maildev-bs
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    environment:
        MAILDEV_IP: "::"
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local