import type {Metadata} from "next";
import React from "react";
import {Navigation} from "@/components/navigation";
import {Footer} from "@/components/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProtectedLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navigation/>
            <main className="container py-8 md:py-12">
                {children}
            </main>
            <Footer/>
        </>
    );
}
