import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import ReactQueryProvider from "@/components/query-client-provider";
import React from "react";
import {Navigation} from "@/components/navigation";
import {Footer} from "@/components/footer";
import {cn} from "@/lib/utils";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn(inter.className)}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
            <ReactQueryProvider>
                {children}
            </ReactQueryProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
