spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_sweeper
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: cicau
    password: cicau
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
#    host: ${EMAIL_HOSTNAME}
#    port: 465
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: "*"
#        starttls:
#          enable: true
#    protocol: smtp
application:
  security:
    jwt:
#      secret-key: ${JWT_SECRET_KEY}
      secret-key: g0ppWGtgAWTww2mBGZ8wNw==MpF6TAt7f6z6m85JUgpk8MrS/4l96qfMlU7aGiSY
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://localhost:4200,http://localhost:8080
server:
  port: 8088
  servlet:
    session:
      cookie:
        max-age: 86394000
aws:
  access:
    key:
#      id: ${AWS_ACCESS_KEY_ID}
  secret:
    access:
#      key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    region: eu-north-1
    bucket:
      name: direct-upload-booksweeper-bucket