name: Pipeline Frontend

on:
  push:
    paths:
      - ui-book-sweeper/**
      - docker/frontend/Dockerfile
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml
      -
jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          cd ui-book-sweeper
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ui-book-sweeper
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/book-sweeper-frontend:${{ steps.extract_version.outputs.VERSION }}